-- MySQL Script generated by MySQL Workbench
-- 11/29/17 16:29:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IoT_House
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IoT_House` DEFAULT CHARACTER SET utf8 ;
USE `IoT_House` ;

-- -----------------------------------------------------
-- Table `IoT_House`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`user_types` (
  `user_types_id` INT NOT NULL AUTO_INCREMENT,
  `user_types_Name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_types_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `IoT_House`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_usr` VARCHAR(20) NULL DEFAULT NULL,
  `user_psw` VARCHAR(20) NULL DEFAULT NULL,
  `user_user_types_id` INT,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_user_types1_idx` (`user_user_types_id` ASC),
  CONSTRAINT `fk_users_user_types1`
    FOREIGN KEY (`user_user_types_id`)
    REFERENCES `IoT_House`.`user_types` (`user_types_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;

-- -----------------------------------------------------
-- Table `IoT_House`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`tokens` (
  `token_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `token_datetime` DATETIME NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `token_user_id` INT NOT NULL,
  PRIMARY KEY (`token_id`),
  INDEX `fk_tokens_users1_idx` (`token_user_id` ASC),
  CONSTRAINT `fk_tokens_users1`
    FOREIGN KEY (`token_user_id`)
    REFERENCES `IoT_House`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `IoT_House`.`process_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`automation_process_status` (
  `automation_process_status_id` INT NOT NULL AUTO_INCREMENT,
  `automation_process_status_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`automation_process_status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

-- -----------------------------------------------------
-- Table `IoT_House`.`automation_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`automation_process` (
  `automation_process_id` INT NOT NULL AUTO_INCREMENT,
  `automation_process_name` VARCHAR(20) NULL DEFAULT NULL,
  `automation_processs_time_start`  DATETIME NOT NULL,
  `automation_process_duration_minutes` INT,
  `automation_process_process_status_id` INT NOT NULL,
  `automation_processs_Monday` INT DEFAULT 0,
  `automation_processs_Tuesday` INT DEFAULT 0,
  `automation_processs_Wednesday` INT DEFAULT 0,
  `automation_processs_Thursday` INT DEFAULT 0,
  `automation_processs_Friday` INT DEFAULT 0,
  `automation_processs_Saturday` INT DEFAULT 0,
  `automation_processs_Sunday` INT DEFAULT 0,
  PRIMARY KEY (`automation_process_id`),
  INDEX `fk_automation_process_process_status_id1_idx` (`automation_process_process_status_id` ASC),
  CONSTRAINT `fk_automation_process_process_status_id1`
    FOREIGN KEY (`automation_process_process_status_id`)
    REFERENCES `IoT_House`.`automation_process_status` (`automation_process_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;

-- -----------------------------------------------------
-- Table `IoT_House`.`pantry_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`pantry_categories` (
  `pantry_category_id` INT NOT NULL AUTO_INCREMENT,
  `pantry_category_name` VARCHAR(20) NULL DEFAULT NULL,
  `pantry_category_order` INT DEFAULT 0,
  PRIMARY KEY (`pantry_category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;

-- -----------------------------------------------------
-- Table `IoT_House`.`pantry_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IoT_House`.`pantry_products` (
  `pantry_product_id` INT NOT NULL AUTO_INCREMENT,
  `pantry_product_name` VARCHAR(30) NULL DEFAULT NULL,
  `pantry_product_needed` INT DEFAULT 0,
  `pantry_product_pantry_category_id` INT NOT NULL,
  `pantry_product_order` INT DEFAULT 0,
  `pantry_product_aisle` INT DEFAULT 0,
  PRIMARY KEY (`pantry_product_id`),
  INDEX `fk_pantry_products_to_pantry_categories1_idx` (`pantry_product_pantry_category_id` ASC),
  CONSTRAINT `fk_pantry_products_to_pantry_categories1`
    FOREIGN KEY (`pantry_product_pantry_category_id`)
    REFERENCES `IoT_House`.`pantry_categories` (`pantry_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;

-- -----------------------------------------------------
-- Table `IoT_House`.`user_types` VALUE INITIALIZATION
-- -----------------------------------------------------
INSERT INTO IoT_House.user_types (user_types_Name) VALUES ('Standart User');

-- -----------------------------------------------------
-- Table `IoT_House`.`process_status` VALUE INITIALIZATION
-- -----------------------------------------------------
INSERT INTO IoT_House.automation_process_status (automation_process_status_name) VALUES ('enabled');
INSERT INTO IoT_House.automation_process_status (automation_process_status_name) VALUES ('disabled');

-- -----------------------------------------------------
-- Table `IoT_House`.`pantry_categories` VALUE INITIALIZATION
-- -----------------------------------------------------
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Panaderia',0);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Cremeria',1);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Lacteos',2);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Abarrotes',3);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Limpieza Hogar',4);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Fruta y verdura',5);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Farmacia',6);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Bebe',7);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Carne',8);
INSERT INTO IoT_House.pantry_categories (pantry_category_name,pantry_category_order) VALUES ('Ferreteria',9);

-- -----------------------------------------------------
-- Table `IoT_House`.`pantry_products` VALUE INITIALIZATION
-- -----------------------------------------------------
-- Panaderia
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pan hamburguesa',1,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pan',1,1);

-- Cremeria
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Salchichas',2,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jamon',2,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Crema',2,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Leche',2,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Mantequilla',2,4);

-- Lacteos
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Queso de mesa',3,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Queso p quesadillas',3,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Queso parmesano',3,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Queso Hamburguesas',3,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Yakult',3,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Yogurt',3,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Panela',3,6);

-- Abarrotes
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cerveza',4,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Refrescos',4,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jugo naranja',4,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cubitos jumex - sofy',4,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Tostadas',4,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Granola',4,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cereal',4,6);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Galletas',4,7);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cereal',4,8);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pan blanco',4,9);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pan tostado',4,10);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cuernitos',4,11);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Chocolate tableta',4,12);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Chocomilk',4,13);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cafe',4,14);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Azucar',4,15);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Caja te 7 asares',4,16);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Harina  hotcakes',4,17);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Maple',4,18);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pasta',4,19);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Mayonesa',4,20);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Chiles jalapeños',4,21);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Salsa casera herdez',4,22);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Salsa taquera herdez',4,23);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Salsa inglesa',4,25);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Salsa magi',4,26);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Tortillas',4,27);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Chiles anchos',4,28);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Canela',4,29);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Arros 1 kg ',4,30);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Platos desechables ondos',4,31);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Platos desechables planos',4,32);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Vasos desechables',4,33);

-- Limpieza hogar
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Servilletas',5,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Papel del higienico',5,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cloro',5,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('pinol',5,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jabon ACE ropa',5,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('fabuloso',5,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Suavitel',5,6);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jabon salvo trastes',5,7);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Aromatizante cuarto',5,8);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Aromatizante refri',5,9);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Placas raidolitos',5,10);

-- Fruta y verdura
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Aderezo para ensala cesar',6,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Huevos',6,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Gotas desinfectantes',6,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cilandro',6,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cebolla',6,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Fruta',6,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Chiles verdes',6,6);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Brocoli',6,7);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Coliflor',6,8);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Calabazita',6,9);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jabon salvo trastes',6,10);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Aromatizante cuarto',6,11);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Aromatizante refri',6,12);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Placas raidolitos',6,13);

-- Farmacia
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Toallas femeninas',7,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pantiprotectores',7,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cotonetes',7,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Gel pelo',7,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Desodorante david',7,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('desodorante candy',7,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jabón para manos',7,6);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Jabon para bañar',7,7);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Shampo David',7,8);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Shampo Candy',7,9);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Shampo Sofia',7,10);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Acondocionador',7,11);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Tinte cabello',7,12);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Toallas humedas',7,13);

-- Bebe 
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Agua',8,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pañales',8,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Toallas húmedas',8,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Papilla',8,3);
  
 -- Carne 
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Bistec',9,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Bistec picado - en su jugo',9,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Carne adobada',9,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Carne molida',9,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Tocino',9,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pechuga pollo',9,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('pollo',9,6);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pollo en milanesa',9,7);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Filetes de pescado',9,8);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Camarones',9,9);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pescado',9,10);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pescado para ceviche',9,11);

-- Ferreteria
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Pegamento 911',10,0);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Manguera',10,1);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Cople manguera ',10,2);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Filtro aspiradora koblens',10,3);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Baterias AAA ',10,4);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Desodorante carro',10,5);
INSERT INTO IoT_House.pantry_products (pantry_product_name,pantry_product_pantry_category_id, pantry_product_order) VALUES ('Franela',10,6);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
